package Models;
// Generated 12/05/2020 15:28:40 by Hibernate Tools 4.3.1



/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private String cpf;
     private String descricao;
     private String dataHoraInicio;
     private String dataHoraFim;
     private String nomeEvento;
     private String qtVagas;
     private String setor;

    public Evento() {
    }

	
    public Evento(String cpf) {
        this.cpf = cpf;
    }
    public Evento(String cpf, String descricao, String dataHoraInicio, String dataHoraFim, String nomeEvento, String qtVagas, String setor) {
       this.cpf = cpf;
       this.descricao = descricao;
       this.dataHoraInicio = dataHoraInicio;
       this.dataHoraFim = dataHoraFim;
       this.nomeEvento = nomeEvento;
       this.qtVagas = qtVagas;
       this.setor = setor;
    }
   
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getDataHoraInicio() {
        return this.dataHoraInicio;
    }
    
    public void setDataHoraInicio(String dataHoraInicio) {
        this.dataHoraInicio = dataHoraInicio;
    }
    public String getDataHoraFim() {
        return this.dataHoraFim;
    }
    
    public void setDataHoraFim(String dataHoraFim) {
        this.dataHoraFim = dataHoraFim;
    }
    public String getNomeEvento() {
        return this.nomeEvento;
    }
    
    public void setNomeEvento(String nomeEvento) {
        this.nomeEvento = nomeEvento;
    }
    public String getQtVagas() {
        return this.qtVagas;
    }
    
    public void setQtVagas(String qtVagas) {
        this.qtVagas = qtVagas;
    }
    public String getSetor() {
        return this.setor;
    }
    
    public void setSetor(String setor) {
        this.setor = setor;
    }




}


