package Models;
// Generated 12/05/2020 15:28:40 by Hibernate Tools 4.3.1



/**
 * Ocorrencia generated by hbm2java
 */
public class Ocorrencia  implements java.io.Serializable {


     private String placa;
     private String dataHora;
     private String descricao;
     private byte[] foto;
     private String tipo;

    public Ocorrencia() {
    }

	
    public Ocorrencia(String placa) {
        this.placa = placa;
    }
    public Ocorrencia(String placa, String dataHora, String descricao,String tipo) {
       this.placa = placa;
       this.dataHora = dataHora;
       this.descricao = descricao;
       this.tipo = tipo;
    }
   
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public String getDataHora() {
        return this.dataHora;
    }
    
    public void setDataHora(String dataHora) {
        this.dataHora = dataHora;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


