package Models;
// Generated 09/05/2020 09:10:42 by Hibernate Tools 4.3.1



/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private String cpf;
     private String nome;
     private String tipo;
     private String senha;

    public Pessoa() {
    }

	
    public Pessoa(String cpf) {
        this.cpf = cpf;
    }
    public Pessoa(String cpf, String nome, String tipo, String senha) {
       this.cpf = cpf;
       this.nome = nome;
       this.tipo = tipo;
       this.senha = senha;
    }
   
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


