package Models;
// Generated 12/05/2020 15:28:40 by Hibernate Tools 4.3.1



/**
 * Veiculo generated by hbm2java
 */
public class Veiculo  implements java.io.Serializable {


     private String placa;
     private String nome;
     private String tipo;
     private String cpfDono;

    public Veiculo() {
    }

	
    public Veiculo(String placa) {
        this.placa = placa;
    }
    public Veiculo(String placa, String nome, String tipo, String cpfDono) {
       this.placa = placa;
       this.nome = nome;
       this.tipo = tipo;
       this.cpfDono = cpfDono;
    }
   
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getCpfDono() {
        return this.cpfDono;
    }
    
    public void setCpfDono(String cpfDono) {
        this.cpfDono = cpfDono;
    }




}


