

import org.hibernate.HibernateException;
import org.hibernate.Session;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MeuComputador
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form FuncionarioEstacionamento
     */
    public Administrador() {
        initComponents();
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        monitorar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        cadastrarEventos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Permissoes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Area de Trabalho do Funcionario Estacionamento");
        setFocusCycleRoot(false);
        getContentPane().setLayout(null);

        jdpPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(jdpPrincipal);
        jdpPrincipal.setBounds(0, 0, 830, 540);

        jMenu3.setText("Monitorar");

        monitorar.setText("Monitorar");
        monitorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitorarActionPerformed(evt);
            }
        });
        jMenu3.add(monitorar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Evento");

        cadastrarEventos.setText("Cadastrar");
        cadastrarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEventosActionPerformed(evt);
            }
        });
        jMenu4.add(cadastrarEventos);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Relatorio");
        jMenuBar1.add(jMenu5);

        Permissoes.setText("Pessoas");

        jMenuItem1.setText("Adicionar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Permissoes.add(jMenuItem1);

        jMenuBar1.add(Permissoes);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 843, 588);
    }// </editor-fold>//GEN-END:initComponents

    private void monitorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitorarActionPerformed
        //Construir interface monitorar
        Monitorar m = new Monitorar();
        //add ao painel desktop
        jdpPrincipal.add(m);
        //tornar visivel
        m.setVisible(true);
  
    }//GEN-LAST:event_monitorarActionPerformed

    private void cadastrarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEventosActionPerformed
        // Construir interface cadastro
        CadastraEvento e = new CadastraEvento();
        //add ao painel desktop
        jdpPrincipal.add(e);
        //tornar visivel
        e.setVisible(true);
        
        
    }//GEN-LAST:event_cadastrarEventosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Construir interface cadastro
        CadastroPessoa p = new CadastroPessoa();
        //add ao painel desktop
        jdpPrincipal.add(p);
        //tornar visivel
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioEstacionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioEstacionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioEstacionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioEstacionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioEstacionamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Permissoes;
    private javax.swing.JMenuItem cadastrarEventos;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenuItem monitorar;
    // End of variables declaration//GEN-END:variables
     
}
