
import Models.Evento;
import org.hibernate.HibernateException;
import org.hibernate.Session;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MeuComputador
 */
public class FuncionarioEstacionamento extends javax.swing.JFrame {

    /**
     * Creates new form FuncionarioEstacionamento
     */
    public FuncionarioEstacionamento() {
        initComponents();
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        monitorar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        cadastrarEventos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        cadastroOcorrencia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Area de Trabalho do Funcionario Estacionamento");
        setFocusCycleRoot(false);
        getContentPane().setLayout(null);

        jdpPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(jdpPrincipal);
        jdpPrincipal.setBounds(0, 0, 830, 540);

        jMenu2.setText("Veiculo");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Cadastro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Monitorar");

        monitorar.setText("Monitorar");
        monitorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitorarActionPerformed(evt);
            }
        });
        jMenu3.add(monitorar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Evento");

        cadastrarEventos.setText("Cadastrar");
        cadastrarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEventosActionPerformed(evt);
            }
        });
        jMenu4.add(cadastrarEventos);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Ocorrencia");

        cadastroOcorrencia.setText("Cadastrar");
        cadastroOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroOcorrenciaActionPerformed(evt);
            }
        });
        jMenu1.add(cadastroOcorrencia);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 843, 588);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
     
         
       
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      CadastroVeiculo c = new CadastroVeiculo();
        jdpPrincipal.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void monitorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitorarActionPerformed
        // TODO add your handling code here:
        //monitorar
        
        Monitorar m = new Monitorar();
        jdpPrincipal.add(m);
        m.setVisible(true);
        monitorar();
        
        
    }//GEN-LAST:event_monitorarActionPerformed

    private void cadastrarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEventosActionPerformed
        // TODO add your handling code here:
        CadastraEvento e = new CadastraEvento();
        jdpPrincipal.add(e);
        e.setVisible(true);
        
        
    }//GEN-LAST:event_cadastrarEventosActionPerformed

    private void cadastroOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroOcorrenciaActionPerformed
        // TODO add your handling code here:
        CadastrarOcorrencia c = new CadastrarOcorrencia();
        jdpPrincipal.add(c);
        c.setVisible(true);
        
    }//GEN-LAST:event_cadastroOcorrenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioEstacionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioEstacionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioEstacionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioEstacionamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioEstacionamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarEventos;
    private javax.swing.JMenuItem cadastroOcorrencia;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenuItem monitorar;
    // End of variables declaration//GEN-END:variables

    private void monitorar() {
       
        try{
            Session s = HibernateUtil.getSessionFactory().openSession();
            String select = "select placa,cpf,data from estacionamento";
            s.createSQLQuery(select);
        }catch(HibernateException e){
            System.out.println("erro"+e);
        }
    }
}
